gltf-rs/gltf

- src/v2/texture.rs
- tests/import_v2.rs
Partial fix for #20:
The tests failed on `Corso.gltf` because it doesn't have `sampler` attributes on its `textures`. According to the spec, the field is not required: https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#texture
> Make texture sampler optional

- CHANGELOG.md
- Cargo.toml
- src/import/binary.rs
- src/import/data.rs
- src/import/from_path.rs
- src/import/mod.rs
- src/import/standard.rs
- src/scene.rs
This removes the `Send + Sync` requirement in the `Source` trait.
> Release version 0.6.1

- src/json/mesh.rs
- src/json/texture.rs
Also: derive PartialEq for json::mesh::Mode.
For usage examples, see https://github.com/bwasty/gltf-viewer/compare/gltf_changes.
> Add `as_gl_enum()` to MagFilter, MinFilter, WrappingMode

- gltf-importer/src/lib.rs
Tiny improvement to enable one-line import: 
```
use gltf_importer::{ Config, ValidationStrategy };
```
> gltf-importer: re-export ValidationStrategy like Config

- clippy.toml
- examples/display/main.rs
- examples/tree/main.rs
- gltf-importer/src/lib.rs
- gltf-importer/tests/import_examples.rs
- gltf-json/src/accessor.rs
- gltf-json/src/buffer.rs
- gltf-json/src/mesh.rs
- gltf-json/src/path.rs
- gltf-json/src/texture.rs
- gltf-json/src/validation.rs
- gltf-json/tests/test_validation.rs
- gltf-utils/src/lib.rs
- src/gltf.rs
- src/lib.rs
- src/mesh.rs
- src/scene.rs
Tip: append [`?w=1`](https://github.com/gltf-rs/gltf/pull/117/files?w=1) to ignore whitespace changes.
I wasn't sure about the `cast_lossless` - theses are the concrete cases: https://gist.github.com/bwasty/21ae877413e4770e4eb5d1b05ebd6284#file-gltf-clippy-txt-L408-L474
> Fix clippy issues

- gltf-utils/src/lib.rs
This PR makes certain operations on `AccessorIter` O(1) and should reduce redundant range checking in `AccessorItem::from_slice`.
> AccessorIter fast paths

- examples/display/main.rs
- examples/tree/main.rs
- gltf-importer/src/lib.rs
- src/glb.rs
- src/gltf.rs
This PR changes refs to Cows to make it possible for Glb to own the data.  The implementation might not be as fast and allocation-low as the old one but this one is shorter and nicer to use.
It also fixes _potential_ oversight of mine in old code where safe code implementing `io::Read::read_exact` could be exposed to uninitialized data which _potentially_ could lead to bad things like leaks of sensitive information, _in theory_.
> Glb::from_reader revamp

- gltf-utils/src/lib.rs
This PR makes it possible to do things like:
```rust
let primitives: Vec<_> = mesh.primitives().flat_map(|x| x.positions(&bins)).collect();
```
which would currently be an error because of overly strict lifetime requirements.  This is solved by introducing additional lifetime `'s`, which prevents `'a` from being coerced to shortest common of `PrimitiveIterator` and `Source`.
> Relax lifetimes in gltf-utils

- gltf-utils/src/lib.rs
I added some iterators for iterating over the `inverseBindMatrices` property of `gltf::Skin` and the input and output sampler data for a `gltf::animation::Channel`. I also implemented `Denormalize` for `i16`.
> Added iterators for inverseBindMatrices and animation channels

- src/lib.rs
This removes the 're-exports' section from the front page of the documentation, replacing with individual items instead.
> Inline top-level re-exports

- gltf-importer/tests/import_examples.rs
- gltf-json/src/accessor.rs
- gltf-utils/src/lib.rs
There's a new sample `SimpleSparseAccessor` that failed to import because some optional fields were not marked correctly.
I also fixed the compilation issues as well as I could (without really understanding the related changes.)
> Fix build issues and bug in sparse accessor parsing

- src/binary.rs
Fixes https://github.com/gltf-rs/gltf/issues/172
Description of the issue copied below.
Glb::to_write pads JSON chunk incorrectly. It uses 0x0, while specification mandates space-characters (0x20)
Quote from specification:
This chunk must be padded with trailing Space chars (0x20) to satisfy alignment requirements.
https://github.com/gltf-rs/gltf/blob/master/src/binary.rs#L151
Binary buffer, however, is padded correctly
This chunk must be padded with trailing zeros (0x00) to satisfy alignment requirements.
> Fix json chunk padding Glb.to_writer

- gltf-json/src/accessor.rs
- gltf-json/src/animation.rs
- gltf-json/src/asset.rs
- gltf-json/src/buffer.rs
- gltf-json/src/camera.rs
- gltf-json/src/image.rs
- gltf-json/src/material.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/scene.rs
- gltf-json/src/skin.rs
- gltf-json/src/texture.rs
Fixes https://github.com/gltf-rs/gltf/issues/173
After these changes (and the now already merged padding fix) I'm able to open serialized binary glTF files in ThreeJS.
Similarly, all empty vectors **must** be left unserialized, but this PR is about `None`s
> Do not serialize None

- Cargo.toml
- gltf-json/Cargo.toml
- gltf-json/src/extensions/material.rs
- gltf-json/src/extensions/mod.rs
- src/material.rs
Refer to [the spec](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md). Not yet tested on real assets; seeking initial feedback.
> Implement KHR_materials_pbrSpecularGlossiness

- gltf-json/src/extras.rs
Fixes injection of an extraneous field into generated JSON.
It'd be nice to skip Extras entirely without going through and tediously cfg-ing every use, but I didn't find a way to do that.
> Skip serializing extras::Void's field

- src/lib.rs
This would have made my debugging of #181 (and a few other issues) go much smoother.
> Propagate detailed error information in Display impl

- gltf-json/src/accessor.rs
- gltf-json/src/animation.rs
- gltf-json/src/asset.rs
- gltf-json/src/buffer.rs
- gltf-json/src/camera.rs
- gltf-json/src/image.rs
- gltf-json/src/material.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/scene.rs
- gltf-json/src/skin.rs
- gltf-json/src/texture.rs
- src/buffer.rs
- src/material.rs
- src/scene/mod.rs
Solves: #189 
Please see the commit messages for the details related to each commit.
Some background:
I'm implementing glTF 2.0 export based on this crate, not export of imported data, export of in-process generated assets. This requires all related data structures to be correctly instantiated by user code. I have also made optional json properties optional and added `serde(skip_serializing_if` attributes for some simple default values. This helps to verify that my test output is identical to the reference models provided by Khronos. The TRS properties also must be made optional to follow the specification, please see the commit messages and links to the related sections of the spec.
I have started to implement some builders to make export easier, that aren't ready yet, but I would like …
> Changes to support glTF 2.0 export/serialization

- gltf-json/src/accessor.rs
- gltf-json/src/extras.rs
- gltf-json/src/root.rs
* Add 'serialize-if-not-none' attribute to `Accessor::min`.
* Add 'serialize-if-not-none' attribute to `Extras::_allow_unknown_fields`.
* Make `Index::new` public.
> Small JSON fixes

- src/accessor/util.rs
- src/buffer.rs
Have found glTF meshes (on Google Poly) that specify 0 byte stride for index buffers which caused debug_assert to be triggered on 0 byte stride when calling `read_indices`.
This should already fail validation, but only the case of `validation_completely` which is typically not run.
With this change we specifically handle the case of byte stride 0 and treat it as if no byte stride was specified to avoid the debug assert and panicking.
> Fix assert on meshes on byte_stride = 0

- src/accessor/mod.rs
Fixes #207. Fixing the issue turned out to be deceptively simple. It was only a matter of removing the unused `view` field from the `Accessor` struct. Previously, reading in the Sponza Atrium model took up to 5 seconds, but with this PR only takes up around 55 milliseconds on my system.
> Fix accessor performance

- gltf-json/src/root.rs
The fix mentioned in my issue #208, this should more clearly show what I mean.
I also noticed making it `Copy` makes it possible to just pass it by value instead, given that it is effectively just an `u32`.
> Make Index<T> Copy for all T

- Cargo.toml
- gltf-derive/Cargo.toml
- gltf-derive/src/lib.rs
- src/image.rs
This PR updates the following outdated dependencies, and fixes the resulting incompatibilities:
- `approx`, 0.1.1 -> 0.3
- `base64`, 0.6 -> 0.10
- `cgmath`, 0.15 -> 0.17
- `image`, 0.19 -> 0.21
- `lazy_static`, 0.2 -> ^1
- `quote`, 0.3 -> 0.6
- `syn`, 0.11 -> 0.15
Updating `quote` requires adding a dependency on `proc_macro2` to `gltf-derive`, but `gltf-json` already transitively requires that anyways.
Updating `image` is slightly complicated by their adding of BGR pixel formats to the `image::DynamicImage` enum. The current PR just adds the new formats to `gltf::image::Format`, though you could, to preserve backwards compatibility, alternatively not add them and report some sort of error when encountered; or, to ensure forwards compatibility, add a hidden __Nonexhaustive variant (see …
> Upgrade Dependencies

- src/binary.rs
- src/import.rs
- src/lib.rs
* Fix incorrect version number in top-level example.
* Note limitations of the `import` function.
* Reword documentation for `Glb::from_reader`.
> Improve documentation

- src/material.rs
The emissive and specular_glossiness texture docs explicitly noted that the values are in sRGB color space, but was missing from base_color_texture. 
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#pbrmetallicroughnessbasecolortexture
> Add sRGB color space docs to base_color_texture

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/roundtrip/main.rs
Writes to `stdout` the JSON portion of a glTF asset as deserialized and serialized by the crate.
> Add gltf-roundtrip example

- gltf-json/src/buffer.rs
- gltf-json/src/extensions/material.rs
- gltf-json/src/extensions/root.rs
- gltf-json/src/extensions/scene.rs
- gltf-json/src/extras.rs
- gltf-json/src/image.rs
- gltf-json/src/material.rs
- gltf-json/src/scene.rs
- src/lib.rs
Fixes warnings reported by `cargo check --all --all-features`.
> Fix compiler warnings

- Cargo.toml
- src/image.rs
- src/lib.rs
> separate import from loading data

- gltf-derive/Cargo.toml
This removes redundantly compiled crates (as imported from serde) speeding up compile times (approximately 2s on my machine).
> Update gltf-derive dependencies

- src/accessor/mod.rs
- src/accessor/sparse.rs
- src/accessor/util.rs
- src/animation/util/mod.rs
- src/mesh/mod.rs
- src/mesh/util/mod.rs
- src/skin/util.rs
> Add sparse accessor iterators

- Cargo.toml
- src/image.rs
- src/lib.rs
This doesn't achieve anything useful at the moment so I would prefer to leave it out of the next release. The crate doesn't include the `import` function with `--no-default-features --features import` and the crate fails to build with `--no-default-features --features import_data_reference`.
This reverts commit eeac166f66a4a8a0df8ba7b863d4cd9e506112d2.
> Revert "separate import from loading data"

- gltf-json/src/animation.rs
I realized the docs here are just copied from the gltf spec, so I made a PR for this myself.
Probably closes https://github.com/gltf-rs/gltf/issues/259
Although I'm still not sure why the catmull rom spline is not in the gltf specs.
> Fix cubic spline docs

- examples/display/main.rs
- examples/roundtrip/main.rs
- examples/tree/main.rs
These warnings were added in a recent rust update.
> Fix warnings in examples

- src/scene/mod.rs
Previously, every accessor method borrowed directly from its object, which makes certain traversals difficult. Instead, we can thread through a single same lifetime representing the root Gltf object.
Only updated `Scene` for now; this should probably be done pervasively, but I didn't want to put in the grunt work without buy-in.
> Relax proxy lifetimes

- src/accessor/mod.rs
- src/accessor/sparse.rs
- src/animation/mod.rs
- src/buffer.rs
- src/camera.rs
- src/image.rs
- src/khr_lights_punctual.rs
- src/material.rs
- src/mesh/iter.rs
- src/mesh/mod.rs
- src/scene/mod.rs
- src/skin/mod.rs
Followup for #264. Tried to get everything, but good odds I missed a few corners.
Aside all the low hanging fruit, I made a couple more significant changes this time: the `Primitives` iterator and the `Primitive` struct itself now capture `Mesh` by value. This increases their size by two pointers in exchange for avoiding narrowing of lifetimes. An alternative approach would be to add a distrinct lifetime parameter for the `Mesh` references alone, but that would be a breaking change, and is less flexible. Considering how trivial these copies should be for LLVM to optimize, I think the chosen solution is ideal.
> Relax additional lifetimes

- src/accessor/util.rs
This trait was implemented for `Iter` prior to 0.14. It appears that
the missing trait implementation was an oversight when sparse
accessors were implemented in #246.
> Implement ExactSizeIterator for accessor::util::Iter

- Cargo.toml
- src/import.rs
When the MIME type is missing gltf can try guessing the file format by using `image::guess_format`.
> Try guessing image format when MIME type is missing or invalid

- src/import.rs
Increase the buffer reservation length by one byte to prevent an extra allocation/copy.
From the `std` lib version of `File::read`:
https://github.com/rust-lang/rust/blob/54b7d21f59a363e53eb1c31d76b40af2ff99321c/src/libstd/fs.rs#L224-L274
```rust
/// Indicates how large a buffer to pre-allocate before reading the entire file.
fn initial_buffer_size(file: &File) -> usize {
// Allocate one extra byte so the buffer doesn't need to grow before the
// final `read` call at the end of the file.  Don't worry about `usize`
// overflow because reading will fail regardless in that case.
file.metadata().map(|m| m.len() as usize + 1).unwrap_or(0)
}
#[stable(feature = "fs_read_write_bytes", since = "1.26.0")]
pub fn read<P: AsRef<Path>>(path: P) -> io::Result<Vec<u8>> {
fn inner(path: &Path) -> …
```
> Prevent an extra allocation and copy per imported file

- gltf-json/src/validation.rs
- src/binary.rs
- src/lib.rs
Fixes these warnings:
```
warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
--> src\lib.rs:560:35
|
560 |             Error::Io(ref e) => e.description(),
```
> Fix deprecation warnings with `std::error::Error::description`.

- src/animation/iter.rs
- src/iter.rs
- src/mesh/iter.rs
- src/scene/iter.rs
- src/skin/iter.rs
The default implementation of `std::iter::Iterator::nth` effectively just calls `next()` for `0..n`. 
```rust
#[stable(feature = "rust1", since = "1.0.0")]
fn nth(&mut self, mut n: usize) -> Option<Self::Item> {
for x in self {
if n == 0 {
return Some(x);
}
n -= 1;
}
None
}
```
The iterators in this crate are adapters over `std::slice::Iter`, which has a specialized version of `nth` to make it `O(1)`. By implementing `nth` and calling the inner iterator method we can effectively turn `nth` into an indexed array access instead of looping through all of the items. 
https://doc.rust-lang.org/src/core/slice/mod.rs.html#3211-3306
```rust
fn nth(&mut self, n: usize) -> Option<$elem> {
if n >= len!(self) {
// This iterator is now empty.
if mem::size_of::<T>() == 0 {
// We have to do it this way …
```
> Implement `nth` for the primary iterators

- Cargo.toml
[Changelog](https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md)
> Update base64 crate v0.11 -> v0.12

- gltf-json/src/material.rs
- src/material.rs
I don't know if this is a welcome change, but I think it should be possible to create _materials_ without an `alphaCutoff` field. 
The reason is that when `"alphaMode" : "BLEND"` is used, this field will be ignored (see this [Issue](https://github.com/KhronosGroup/glTF/issues/1158)).
Therefore the Khronos **glTF-Validator** shows this warning, when the `alphaCutoff` field is present and the `alphaMode` is `BLEND`:
There are also official [examples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) where this field is ommited for `"alphaMode" : "BLEND"`.
Apart from that I changed the Documentation comment for `"BLEND"` to the following, because it seems it was previously just copied from `"MASK"`:
> The alpha value is used, to determine the transparency …
> Make alpha cutoff optional.

- gltf-json/src/mesh.rs
The GLTF standard requires every mesh to contain a `primitives` property. Also, several importers, such as Blender's GLTF import, fail when a mesh does not contain the `primitives` property.
By skipping the serialization of `primitives` property when it is empty, exporting empty meshes will result in an invalid GLTF file. This change removes this attribute so that the `primitives` property is always exported, even when it is empty.
Honestly, this such a minor detail that it's probably not even worth worrying about, as it won't even affect the vast majority of people. The only reason I even noticed this is because I'm writing a modding tool for a game that, for some reason, has empty meshes in certain levels.
> Fixed invalid mesh export when 'primitives' is empty.

- src/lib.rs
Hey! This fixes what looks like copy-paste errors in `Normalize` for `u8`
* The `impl Normalize<f32> for u8` was causing `u8` vertex colors to appear black, and now exhibits the correct behavior.
* The `impl Normalize<u16> for u8` I did not test, but it follows the patterns of the other integer `Normalize` implementations.
> Fix `Normalize` for `u8`

- .github/workflows/test.yml
~Also pulls the KhronosGroup/glTF-Sample-Models repository only during tests.~
Just adding the github action for now, removing submodule in another PR
> Migrate tests to GitHub Actions

- Cargo.toml
Latest are always best? :)
(also less likely to cause duplicates for dependent crates)
> Update dependencies: base64 and approx

- examples/export/main.rs
I ran into this when using this function as a reference for a project, and accidentally overlooked the hardcoded min/max values. So I thought I'd contribute this to upstream for the next person wanting to use this as a reference :)
> Export example: calculate bounding coordinates instead of using hardcoded values

- src/accessor/util.rs
This could easily happen if the binary data for the glTF was too short or empty.
Ideally should return a `Result` and enum error for this rather than just `Option::None` but this is a pretty easy change at least and better than panicking.
Part of #359
> Fix panic on data slice accesses

- CHANGELOG.md
- examples/export/main.rs
This fixes the bounds calculation in the export example.
> Fix bounds calculation in export example

- gltf-json/src/root.rs
These additional trait implementations will allow `Index`es to be stored in maps and compared with others, which will be useful at least for my purposes in generating glTF and testing the generator.
While I was looking at the code, I also eliminated the `unsafe impl`s by changing the phantom type from `PhantomData<*const T>` to `PhantomData<fn() -> T>`, which avoids the `!Send` that phantom `*const T` causes. This is a separate commit and could be split to a separate PR if desired.
> Implement `Eq`, `Ord`, and `Hash` for `gltf_json::Index`.

- gltf-json/src/extensions/material.rs
`KHR_materials_volume` needs `Validate`, `texture`, and `extras`, but those items were not imported when exactly that feature was enabled.
To fix this and any other similar problems, and prevent reoccurrences, make the `use` unconditional, with `#[allow(unused_imports)]` to avoid warnings when the relevant features are not enabled.
> Fix compilation with `KHR_materials_volume` feature only.

- Cargo.toml
This dependency is actually only used with feature `import`
> Make `urlencoding` optional

- README.md
Saw that there was a missing supported extension in the README.md list :)
> Add transmission ext. support to list of extensions

- CHANGELOG.md
- examples/export/main.rs
- gltf-json/src/mesh.rs
- gltf-json/src/validation.rs
- src/mesh/iter.rs
HashMap uses a hash function that behaves differently based on the moment of the initialization of the program. That leads to the different iteration orders during serialization. Replacing HashMap with BTreeMap fixes the issue
> Fix Primitive::attributes serialization determinism issue

- src/import.rs
- src/lib.rs
Fixes #222. New public API:
* `gltf::import` module (debatable: it would also be possible to keep this private and re-export the other functions)
* `gltf::import::import` and `gltf::import::import_slice`: These were already available as `gltf::import` and `gltf::import_slice` but now you can also see them at this path
* `gltf::import::{import_buffer_data, import_image_data}`: These already existed but they are now `pub`. This is the part that actually fixes #222.
* `gltf::buffer::Data::{from_source, from_source_and_blob}`: This allows importing just one buffer and getting errors about it. Note that `import::Scheme` is *not* made public here.
* `gltf::image::Data::from_source`: Same thing but for images. Most of the logic from `import_image_data` is now in this function.
> Add more public import facilities

- examples/export/main.rs
- gltf-json/src/accessor.rs
- src/accessor/mod.rs
- src/accessor/util.rs
This fixes validation of sparse accessors without buffer_views, which must not have a byte_offset. This is not explicit in the spec but is in the official validator (see https://github.com/KhronosGroup/glTF-Validator/issues/207)
> Make byte_offset optional for sparse accessors

- examples/export/main.rs
- gltf-json/src/scene.rs
Since `Node`s are generally expected to have only a few non-absent fields, providing this `Default` implementation will allow code that is generating `Node`s to be much more concise.
> `impl Default for gltf_json::Node`.

- CHANGELOG.md
- src/accessor/util.rs
- tests/test_wrapper.rs
In #313 @wsw0108 shows that collecting positions specified using a sparse accessor triggers a panic (`attempt to subtract with overflow`) inside of `size_hint()` of `SparseIter`.
In this PR I have rewritten the code in the issue as two unit tests, one that verifies `size_hint()` and one that verifies that the positions are actually correct. Both tests fail when using latest `main`.
The `SimpleSparseAccessor.gltf` test asset contains 14 positions specified in a sparse accessor where three of them is overrideen by values specified in the sparse section of the accessor. Look at the data layout image here for an overview: [gltf-test/tutorialModels/SimpleSparseAccessor][1].
The two tests pass after delegating the `size_hint()` call to the iterator for the base accessor, it knows how many items …
> Fix size hint and values read with sparse iterator

- src/lib.rs
Currently, when serializing a glTF `Document`, the responsible code must own the `Document` to call the `into_json` method. However, this requirement deviates from the usual read-only borrow requirement for serializing data. To overcome this, client code can arrange for passing around references to the inner `Root` struct, but doing so sacrifices the benefits provided by the `Gltf` and `Document` structs for better binary data handling. (The `Deref` implementation for `Gltf` can also be used, but its syntax is somewhat unintuitive, and that does not apply to `Document`s themselves.)
To improve on this, let's introduce a non-consuming `as_json` unwrapping method. This method takes the `Document` by reference and returns a reference to the inner `Root` structure. By doing this, its usage …
> Add non-consuming `as_json` method to `Document` struct

- CHANGELOG.md
- Cargo.toml
`image` released a `0.25.0` version. Most notably, they switched the jpeg decoder backend to `zune-jpeg` and removed the feature `jpeg_rayon`. This PR updates `image` and removes the associated `image_jpeg_rayon` feature. All tests pass. I have not seen other relevant changes in the `image` release notes for `gltf` but I'm not familiar with the codebase.
> Bump image to 0.25.0

- src/animation/iter.rs
- src/animation/mod.rs
This adds `.index()` to `gltf::animation::Channel` and `gltf::animation::Sampler`.
This should fix #398.
> feat: Channel and Sampler return their index with .index(). Fixes #398

- README.md
Was reading the readme and thought webp was unsupported, but after some quick greps, it seems like it is actually supported. Made it clear in the readme.
> Mention that EXT_texture_webp is supported in the readme.

- Cargo.toml
- examples/export/main.rs
The function `to_padded_byte_vector()` is unsound because:
* It accepts an arbitrary `Vec<T>` without checking that `T` contains no padding, which is UB to read in any way including by reinterpreting as `u8`s.
* It produces a `Vec` which thinks it has a different alignment than the allocation was actually created with.
To fix these problems, this change:
* Uses `bytemuck` to check the no-padding condition.
* Creates a new `Vec` instead of trying to reuse the existing one. (Conditional reuse would be possible, but more complex.)
An alternative to using `bytemuck` would be to make `to_padded_byte_vector()` an `unsafe fn` (or to accept `Vertex` only instead of `T`). However, I think it is valuable to demonstrate how to do this conversion using safe tools, to encourage people to use safe code …
> examples/export: Replace unsound `to_padded_byte_vector()` implementation with `bytemuck`.

- src/image.rs
`data.format` and `let pixels = image.into_bytes()` seems to imply that the doc comment is outdated. Could be a point of confusion.
> docs: change potentially confusing doc comment
