gltf-rs/gltf

- .travis.yml
As the title says, this is to remove the requirement for sudo
> Update travis to not use sudo

- src/v2/buffer.rs
- src/v2/material.rs
- src/v2/mesh.rs
- src/v2/scene.rs
- tests/import_v2.rs
- tests/minimal.gltf
All changes were verified against the current spec draft. This should resolve #20.
> Fix several issues revealed by new 2.0 sample models

- .gitignore
- Cargo.toml
- gltf_derive/Cargo.toml
- gltf_derive/LICENSE
- gltf_derive/src/lib.rs
- src/lib.rs
- src/v2/import.rs
- src/v2/json/accessor.rs
- src/v2/json/animation.rs
- src/v2/json/asset.rs
- src/v2/json/buffer.rs
- src/v2/json/camera.rs
- src/v2/json/extras.rs
- src/v2/json/image.rs
- src/v2/json/material.rs
- src/v2/json/mesh.rs
- src/v2/json/mod.rs
- src/v2/json/root.rs
- src/v2/json/scene.rs
- src/v2/json/skin.rs
- src/v2/json/texture.rs
- src/v2/validation.rs
> Validate trait implementation

- src/gltf.rs
- src/scene.rs
> Implement ExactSizeIterator for common iterator types

- Cargo.toml
- src/lib.rs
- src/mesh.rs
> Implement ExactSizeIterator for primitive iterators

- .gitmodules
Let's see if the build succeeds...
> Make sample models submodule non-shallow again

- .gitmodules
- CHANGELOG.md
- Cargo.toml
- README.md
- gltf-derive/Cargo.toml
- gltf-importer/Cargo.toml
- gltf-importer/src/lib.rs
- gltf-json/Cargo.toml
- gltf-json/src/scene.rs
- gltf-utils/Cargo.toml
- src/gltf.rs
- src/lib.rs
- src/scene.rs
> Add scene::Transform

- .travis.yml
- Cargo.toml
- src/gltf.rs
- src/lib.rs
- src/scene.rs
> Fix Transform::decomposed

- src/gltf.rs
> Add size_hint to gltf::Images

- .travis.yml
> Add travis_wait to travis config

- gltf-utils/src/lib.rs
> Fix JointsU16

- src/mesh.rs
> Replace Attribute type with tuple

- gltf-importer/src/lib.rs
> Add FileNotFound error kind

- gltf-utils/src/lib.rs
> PrimitiveIterator::joints_u16() retrieves Semantic::Joints(set) instead of Semantic::Colors(set)

- gltf-utils/src/lib.rs
This PR adds some tests which test `AccessorIter` and its fast paths.  In addition, this also removes redundant `accessor` field of `AccessorIter` and fixes bug in `AccessorIter::size_hint` which also affects `AccessorIter::count`.
> Tests for AccessorIter and AccessorItem

- gltf-utils/src/lib.rs
By request in #141  `ChannelIterators` now has a method `outputs` that returns an `enum` containing the iterator for the channel data based on the type of data.
> Refactored gltf-util ChannelIterators based on Issue #141

- gltf-json/src/material.rs
- src/material.rs
> Fix metallic_roughness_texture docs

- src/gltf.rs
Nothing major, but still, worth fixing IMO. xP
Thank you guys for making this crate!
> Fix small documentation mistake

- gltf-json/src/validation.rs
Simple 1-line change to add some more impls for the error type.
> Add some derives for the error type

- Cargo.toml
- gltf-derive/Cargo.toml
- gltf-json/Cargo.toml
Version 0.11.0 will be yanked as it is completely broken.
> Version 0.11.1

- gltf-json/src/animation.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/scene.rs
- gltf-json/src/skin.rs
Fixes issue https://github.com/gltf-rs/gltf/issues/176
> Do not serialize Vecs that are empty

- Cargo.toml
- README.md
- examples/export/main.rs
> Add export example

- gltf-json/Cargo.toml
- gltf-json/src/extras.rs
For testing https://github.com/serde-rs/json/issues/355.
> Expose Extras as RawValue

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/math.rs
- src/scene/mod.rs
> Remove dependency on cgmath

- CHANGELOG.md
- Cargo.toml
- gltf-json/Cargo.toml
- gltf-json/src/extensions/mod.rs
- gltf-json/src/extensions/root.rs
- gltf-json/src/extensions/scene.rs
- gltf-json/src/extras.rs
- gltf-json/src/validation.rs
- src/iter.rs
- src/khr_lights_punctual.rs
- src/lib.rs
- src/scene/mod.rs
> Implement KHR_lights_punctual

- gltf-json/src/animation.rs
- gltf-json/src/camera.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/validation.rs
- src/binary.rs
> annotate trait objects with dyn

- src/material.rs
> Give gltf::material::Material Clone & Debug derives.

- src/import.rs
- src/lib.rs
New version of #192 potentially a bit better
The error name is maybe not ideal
> Add slice import 

- gltf-json/src/animation.rs
Removes CatmullRomSpline as discussed in https://github.com/gltf-rs/gltf/issues/259
> Remove CatmullRomSpline

- Cargo.toml
- src/accessor/mod.rs
- src/animation/mod.rs
- src/buffer.rs
- src/camera.rs
- src/image.rs
- src/lib.rs
- src/material.rs
- src/mesh/mod.rs
- src/scene/mod.rs
- src/skin/mod.rs
> Have docs.rs document all features

- src/import.rs
I have data in this form:
```
"buffers" : [
{
"byteLength" : 160244,
"uri" : "data:application/octet-stream;base64,wsVHPgAAgD++FHu/ws...
```
Currently if trying to load this data using `gltf::import_slice(&bytes)` this will fail because as the code is written, it assumes a non-None path
I think it would be more accurate to move this check into the read() function allowing for the base64 case to work with a None path.
> Support URIs with embedded data when importing from a slice

- src/lib.rs
Very minor change to documentation to remove older version number.
> Minor change for version number in documentation

- CHANGELOG.md
- Cargo.toml
- src/import.rs
- tests/import_sanity_check.rs
> Fix relative imports with spaces

- gltf-json/src/accessor.rs
- gltf-json/src/animation.rs
- gltf-json/src/asset.rs
- gltf-json/src/buffer.rs
- gltf-json/src/camera.rs
- gltf-json/src/extensions/material.rs
- gltf-json/src/extensions/scene.rs
- gltf-json/src/extensions/texture.rs
- gltf-json/src/image.rs
- gltf-json/src/material.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/scene.rs
- gltf-json/src/skin.rs
- gltf-json/src/texture.rs
...when extras feature is disabled.
Fixes #230
> Don't serialize `Extras`

- src/lib.rs
Sorry, was a bit fast on merging #334 , i wanted to remove panics asap.
> Better UnsupportedImageFormat error message

- src/image.rs
Thanks for the good crate!
Bumped into a tiny docstring discrepancy, and thought creating a PR is as easy as creating an issue for it.
> fix image::Data width and height docstrings

- src/accessor/mod.rs
- src/lib.rs
- src/mesh/mod.rs
Looks like I missed these in #375.
> Fix doctests

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
- gltf-json/Cargo.toml
- gltf-json/src/animation.rs
- gltf-json/src/texture.rs
- tests/import_sample_models.rs
The JSON parsing will succeed but the validation checks will fail.
> Allow animation target node to be empty

- gltf-json/src/accessor.rs
- gltf-json/src/animation.rs
- gltf-json/src/buffer.rs
- gltf-json/src/camera.rs
- gltf-json/src/material.rs
- gltf-json/src/mesh.rs
- gltf-json/src/root.rs
- gltf-json/src/texture.rs
Steps to reproduce :-
cd gltf/gltf-json
cargo clippy --fix --lib -p gltf-json
This fixes a small niggle ... many many times..
> Ran cargo clippy --fix
